### ISSUE TITLE
Globals in dist/app.js

### ISSUE THREAD

**Issue by SrsBusiness** [nickroberts404/cs373-idb#30]
As I understand it gulp more or less concatenates all of our Javascript files into one app.js file that then gets loaded on our web page. A lot of the constituent Javascript files use the same names for local variables, and I'm a little concerned about the consequences of overloading those globals.

**Comment by nicorobo** [comment]
Instead of concatenating our files, we're using Browserify to modularize our files and bundle them. Each file is treated as its own module with its own namespace that can be depended upon by other "modules", very similar to python's module system.
