### ISSUE TITLE
Planning poker

### ISSUE THREAD

**Issue by bdholder** [nickroberts404/cs373-idb#50]
Use [http://www.planitpoker.com](http://www.planitpoker.com) or [https://www.planningpoker.com](https://www.planningpoker.com) to:
- set up at least 10 user stories
- user stories must be described in three sentences or less
- estimate them, include assumptions
- discuss them
- refine the estimates
- implement them
- track how long each took
- document them in your GitHub Wiki

**Comment by nicorobo** [comment]
http://www.planitpoker.com/board/#/room/d89a1319a1dc447981e1b51391fe5a72

**Comment by bdholder** [comment]
[Planning Poker Page Mark 2](http://www.planitpoker.com/board/#/room/7541dabf459a4c6bbca4a1377133234c)
