### ISSUE TITLE
Fix search from search results page

### ISSUE THREAD

**Issue by ghost** [nickroberts404/cs373-idb#57]
When you try and do a new search from the search results page it doesn't work

**Comment by nicorobo** [comment]
I'm not sure why, but search from the search page works fine when clicking `enter`, but still doesn't work when using the 'Go' button.

**Comment by SrsBusiness** [comment]
bizarre...

**Comment by SrsBusiness** [comment]
hitting enter should be the same as clicking the "Go" link...

**Comment by nicorobo** [comment]
The data was only being fetched when the component is mounted. Updating state doesn't cause the component to remounted. 
It worked when pressing `enter` because for some reason, the enter key refreshed our page by default when focused on the input box, and we weren't preventing default behaviour.
